config/routes.rb
Rails.application.routes.draw do
  resources :livros
  resources :alunos
  resources :emprestimos
  root 'alunos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
  acts_as_paranoid
  
  has_one :livro
  has_many :emprestimos

  validates_presence_of :nome

  def livro_atual
    livro.nil? ? "Nenhum livro com o aluno" : livro.nome
  end

  def self.sem_livros
    includes(:livro).references(:livro).where("livros.id IS NULL")
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emprestimo.rb
class Emprestimo < ApplicationRecord
  belongs_to :aluno, :with_deleted => true
  belongs_to :livro, :with_deleted => true

  validates_presence_of :aluno_id, :livro_id

  scope :abertos, -> { where(data_devolucao: nil) }

  after_create :setar_aluno

  def setar_aluno
    livro.update_column(:aluno_id, aluno_id)
  end

  def limpar_aluno
    livro.update_column(:aluno_id, nil)
  end

  def devolver!
    update_column(:data_devolucao, Date.today)
    limpar_aluno
  end

  def aluno_nome
    "#{aluno.nome}#{(" (Removido)" if aluno.deleted?)}"
  end

  def livro_nome
    "#{livro.nome}#{( "(Removido)" if livro.deleted?)}"
  end

  def data_devolucao
    self[:data_devolucao].strftime("%d/%m/%Y") if self[:data_devolucao]
  end

  def data_emprestimo
    self[:data_emprestimo].strftime("%d/%m/%Y")
  end

end

app/models/livro.rb
class Livro < ApplicationRecord
  acts_as_paranoid
  scope :disponiveis, -> { where(aluno_id: nil) }

  validates_presence_of :nome,:autor,:edicao
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos =
      if params[:campo_busca].nil?
        Aluno.all
      else
        Aluno.where("nome like ?","%#{params[:campo_busca]}%")
      end
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
    @emprestimo =
      if @aluno.livro
        @aluno.emprestimos.abertos.first
      else
        nil
      end
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno criado com sucesso.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :livro_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emprestimos_controller.rb
class EmprestimosController < ApplicationController
  def index
    @emprestimos = Emprestimo.all
  end

  def new
    @emprestimo = Emprestimo.new
    @alunos = Aluno.sem_livros
    @livros = Livro.disponiveis
  end

  def create
    @emprestimo = Emprestimo.new(emprestimo_params)
    @emprestimo.data_emprestimo = Date.today

    respond_to do |format|
      if @emprestimo.save
        format.html { redirect_to emprestimos_url, notice: 'Empréstimo criado com sucesso.' }
        format.json { render :show, status: :created, location: @emprestimo }
      else
        format.html { render :new }
        format.json { render json: @emprestimo.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @emprestimo = Emprestimo.find(params[:id])

    respond_to do |format|
      if @emprestimo.devolver!
        format.html { redirect_to emprestimos_url, notice: 'Devolução efetuada com sucesso.' }
        format.json { render :index, status: :created, location: @emprestimo }
      else
        format.html { render :new }
        format.json { render json: @emprestimo.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emprestimo
      @emprestimo = Emprestimo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emprestimo_params
      params.require(:emprestimo).permit(:aluno_id, :livro_id)
    end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:show, :edit, :update, :destroy]

  # GET /livros
  # GET /livros.json
  def index
    @livros = Livro.all
  end

  def index
    @livros =
      if params[:campo_busca].nil?
        Livro.all
      else
        Livro.where("nome like ?","%#{params[:campo_busca]}%")
      end
  end

  # GET /livros/1
  # GET /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: 'Livro criado com sucesso.' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: 'Livro removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:nome, :autor, :edicao)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def helper_busca url, params
    "<div class=busca>
      #{form_tag(url, params) do
        concat(text_field_tag('campo_busca'))
        concat(submit_tag('Buscar'))
      end}
    </div>".html_safe
  end
end

app/helpers/emprestimo_helper.rb
module EmprestimoHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/alunos/_form.html.erb
<%= form_for(aluno, validate: true) do |f| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<%= helper_busca(alunos_url, method: "get")%>

<table width="100%">
  <thead>
    <tr>
      <th width="50%">Nome</th>
      <th width="40%">Livro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.livro_atual %></td>
        <td><%= link_to 'Mostrar', aluno %></td>
        <td><%= link_to 'Editar', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Remover', aluno, method: :delete, data: { confirm: 'Tem certeza que deseja excluir este aluno?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>Novo Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Voltar', alunos_path %>

app/views/emprestimos/_form.html.erb
<%= form_for(emprestimo, validate: true) do |f| %>
  <% if emprestimo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emprestimo.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% emprestimo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aluno %>
    <%= f.select(:aluno_id, @alunos.map{|x| [x.nome, x.id]}) %>
  </div>

  <div class="field">
    <%= f.label :livro %>
    <%= f.select(:livro_id, @livros.map{|x| [x.nome, x.id]}) %>
  </div>

  <div class="actions">
    <%= f.submit "Criar Empréstimo" %>
  </div>
<% end %>

app/views/emprestimos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empréstimos</h1>

<table width="100%">
  <thead>
    <tr>
      <th width="50%">Aluno</th>
      <th width="40%">Livro</th>
      <th width="5%">Data de Empréstimo</th>
      <th width="5%">Data de Devolução</th>
    </tr>
  </thead>

  <tbody>
    <% @emprestimos.each do |emprestimo| %>
      <tr>
        <td><%= emprestimo.aluno_nome %></td>
        <td><%= emprestimo.livro_nome %></td>
        <td><%= emprestimo.data_emprestimo %></td>
        <td><%= emprestimo.data_devolucao.nil? ? link_to('Devolver Livro', edit_emprestimo_path(emprestimo)) : emprestimo.data_devolucao %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Empréstimo', new_emprestimo_path %>

app/views/emprestimos/new.html.erb
<h1>Novo Empréstimo</h1>

<%= render 'form', emprestimo: @emprestimo %>

<%= link_to 'Voltar', emprestimos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class=menu>
      <%= link_to 'Alunos', alunos_path %>
      <%= link_to 'Livros', livros_path %>
      <%= link_to 'Empréstimos', emprestimos_path %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/livros/_form.html.erb
<%= form_for(livro, validate: true) do |f| %>
  <% if livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :autor %>
    <%= f.text_field :autor %>
  </div>

  <div class="field">
    <%= f.label "Edição" %>
    <%= f.number_field :edicao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/livros/edit.html.erb
<h1>Editando Livro</h1>

<%= render 'form', livro: @livro %>

<%= link_to 'Mostrar', @livro %> |
<%= link_to 'Voltar', livros_path %>

app/views/livros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Livros</h1>

<%= helper_busca(livros_url, method: "get")%>

<table>
  <thead>
    <tr>
      <th width="50%">Nome</th>
      <th width="35%">Autor</th>
      <th width="5%">Edição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @livros.each do |livro| %>
      <tr>
        <td><%= livro.nome %></td>
        <td><%= livro.autor %></td>
        <td><%= livro.edicao %></td>
        <td><%= link_to 'Mostrar', livro %></td>
        <td><%= link_to 'Editar', edit_livro_path(livro) %></td>
        <td><%= link_to 'Remover', livro, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Livro', new_livro_path %>

app/views/livros/new.html.erb
<h1>Novo Livro</h1>

<%= render 'form', livro: @livro %>

<%= link_to 'Voltar', livros_path %>

app/views/livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @livro.nome %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>

<p>
  <strong>Edição:</strong>
  <%= @livro.edicao %>
</p>

<%= link_to 'Editar', edit_livro_path(@livro) %> |
<%= link_to 'Voltar', livros_path %>